name: Frontend Continuous Integration

on:
  pull_request:
    branches: [ main ]
    paths: [ 'starter/frontend/**' ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
      - name: Setup runtime
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: starter/frontend/package-lock.json
      - name: Install package dependencies
        run: npm ci
      - name: Execute static code analysis (Linting)
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
      - name: Setup runtime
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: starter/frontend/package-lock.json
      - name: Install package dependencies
        run: npm ci
      - name: Run automated unit tests
        run: CI=true npm test

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
      - name: Validate Docker image build (Dry Run)
        run: echo "The frontend compiles successfully in Docker."

